# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee6a37baa53adf2e86b782dfef139aed23dcd08ba27b16cbc20c689159ca3e096a4a62ce3eccdbd67da5cf1a7c4f7a327a79a6c1af398626892e030532e49ae

test:
  secret_key_base: bb4f31a988561da6e32b73fdf4f011c17fadae4dc358a0accc91e9d59b8fcce4ff5a7893409ffac249c395d1552d196485611f61cf20b3cec8832637019a625c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
